---
title: "Colorado_Results"
author: "Marcela Suárez"
date: "July 18, 2019"
output: html_document
---

## Intro

This document present the results obtained for Colorado:

```{r import_data, include=FALSE}

library(tidyverse) 
colorado <- read_csv("ColoradoFloodOriginal.csv") # Loading data into R

 # Create a subset with the variables to be used
library(lubridate) # For dates
colorado <- colorado %>% 
  mutate(date = ymd_hms(colorado$created_at, tz="UTC")) %>% 
  select(lat = latitude, 
         lon = longitude, 
         date = date, 
         state = c_state,
         text = t_text)
```

##  Define temporal stages in a tidy way

```{r define_temporal_stages}

max(colorado$date) # Just for information
min(colorado$date) # Just for information

colorado <- colorado %>% 
  mutate(stage = ifelse(date <= "2013-09-11 00:00:00 PDT", "preflood",
                        ifelse(date <= "2013-09-16 00:00:00 PDT", "flood",
                               ifelse(date <= "2013-09-23 00:00:00 PDT", "immediate_aftermath", "postflood")))) %>%
    mutate(stage = factor(stage, levels = unique(stage))) # Turning stages into factors to use them for plotting later

```

## Convert this dataset so that it has one-token-per-document-per-row

```{r remove_retweets}

library(tidytext)
library(stringr)

colorado <- colorado %>% 
  filter(!str_detect(text, "^RT")) # There will remain some retuits since those will be commented retweets (actually adding some info)
```

```{r clean_tweets}

colo_clean <- colorado %>% 
   mutate(text = str_remove_all(text, 'http[^ ]+'), #Finally removing urls in a nice way
          text = str_remove_all(text, '@[^ ]+'), # Removing usernames
          text = str_remove_all(text, "[:punct:]"), # Removing puntuation
          text = str_remove_all(text, "[:digit:]")) # Removing numbers
```

```{r one-token-per-document-per-row, echo=FALSE}

colo_tidy <- colo_clean %>% 
  mutate(tweet = text) %>% # To keep a column with the original tweet
  unnest_tokens(word, text, token = "tweets") %>% # add a row for each token (word) and repeat the other information
  anti_join(stop_words) %>% # remove stopwords
  filter(word != "boulder") # Based on what we saw at counting words in the next line. Next two candidates are Im and boulderflood. TO CHECK LATER!

colo_tidy %>% 
  count(word, sort = TRUE) # Count words
```

```{r explore_tf_idf}

colo_tf_idf <- colo_tidy %>% 
  count(stage, word, sort = TRUE) %>% 
  bind_tf_idf(word, stage, n) %>% 
  group_by(stage) %>% 
  top_n(9) %>% 
  ungroup 

colo_tf_idf %>% 
  mutate(word = reorder(word, tf_idf)) %>% 
  ggplot(aes(word, tf_idf, fill = stage)) +
  geom_col(alpha = 0.8, show.legend = FALSE) +
  facet_wrap(~stage, scales = "free") +
  coord_flip()
  
```


